doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'App\Database\Migrations': '%kernel.project_dir%/src/Database/Migrations'
    enable_profiler: false

    storage:
        # Default (SQL table) metadata storage configuration
        table_storage:
            table_name: 'database_migrations'
            version_column_name: 'version'
            version_column_length: 192
            executed_at_column_name: 'executed_at'
